baseURL = 'https://emok.vercel.app/'
languageCode = 'en-us'
title = 'Enoch Mok'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Enoch's Personal Website"

# Appearance settings
theme = 'auto'
colorPalette = 'base16-ocean'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'hello! ğŸ‘‹ğŸ»'
homeIntroContent = """

I'm an aspiring Data Scientist. I live for [coffee](/things/my_caffeine_addiction), good food, sunsets and oceans.

This site is the HTML version of what's happening in my head.

If you're an organised mess too, don't leave me hanging! ğŸ‘ŠğŸ»

----
"""

# Footer
showFooter = true

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "$ ~"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/enochmok/"

[[params.social]]
name = "github"
url = "https://github.com/e-mny"

[[params.social]]
name = "telegram"
url = "https://t.me/ahmokahmok"

[[params.social]]
name = "resume"
url = "/EnochMok_Resume.pdf"

# Main menu pages
[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "projects"
url = "/projects"

[[params.menu]]
name = "things"
url = "/things"

[[params.menu]]
name = "z_tags"
url = "/tags"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'
